env:
  es6: true
  node: true

extends:
  - eslint:recommended
  - airbnb-base
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  # - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier/@typescript-eslint
  - prettier # must go last, to turn off some previous rules

rules:
  prefer-arrow-callback: error
  func-names: off
  no-use-before-define: off
  require-await: error
  '@typescript-eslint/no-use-before-define': off

ignorePatterns:
  - dist

overrides:
  - files: ['**/*.ts']
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 2018
      sourceType: module

  - files:
      - '**/*.config.js'
      - '**/jest.config.js'
      - '**/tsconfig.*.js'
      - '**/webpack.*.js'
      - '**/rollup.*.js'
      - '**/vite.config.js'
      - '**/.*rc.js'
      - '**/*.eslintrc.js'
    parser: espree
    parserOptions:
      ecmaVersion: 2020
      sourceType: script
    rules:
      '@typescript-eslint/*': off
      '@typescript-eslint/no-throw-literal': off
